### ISSUE TITLE
image files don't show up in right-hand panel

### ISSUE THREAD

**Issue by planaria158** [jakebian/quiver#26]
Started quiver and it appears to launch normally. My model is visible in the left pane. However, no files visible on the right pane (path is correctly set and there are legit image files present). 

Any thoughts? 

I'm using Chrome on a Mac; keras 1.1.1; installed quiver via pip. 

Perhaps its a browser issue?

**Comment by isaacgerg** [comment]
The paths are not working correctly.  This is a duplicate of another issue.

**Comment by planaria158** [comment]
Thanks Isaac.  I looked at the duplicate issue you refer to as well as issue #9.  I looked at server.py and it seems to me that it should work on a linux or OSx system.  I see how the hardwired path separators would cause trouble on Windows.  

The demo video on YouTube is clearly running on a linux or Mac.

So, I'm still unclear why I can't see any of the image files in the current directory when I launch.

I've tried Chrome and Firefox: both give same result.

**Comment by jakebian** [comment]
Should be fixed by https://github.com/jakebian/quiver/commit/798f98fc8292c2b61d9c20394434875462a5c370, @planaria158 verify when you get a chance

**Comment by planaria158** [comment]
Thanks Jake!  Image files are now visible and can be selected.

One small problem persists:

I'm trying a 'standard' example to make sure it works end-to-end for me.

from quiver_engine import server
from keras.applications import VGG16
model = VGG16()
server.launch(model, port=7000)

When I select an image (that is 224x224) RGB png file, I get the following error:

_Exception: Error when checking : expected input_4 to have shape (None, 3, 224, 224) but got array with shape (1, 3, 3, 224)_

**Comment by jakebian** [comment]
@planaria158 sounds like your image isn't being preprocessed correctly. Does it work with other images? This is a separate issue so you should open a new issue posting your image and your model, so that we can help you troubleshoot

**Comment by planaria158** [comment]
Found the problem.  The ordering in keras.json matters.  If I change it from "th" to "tf", then the VGG16 model works fine with Quiver.

**Comment by rajshah4** [comment]
I also had problems with my images not showing.  I figured out it was due to my image files having the extension .jpeg.  I renamed them to .jpg and everything worked fine.  It might be good to note somewhere that image files are assume to have a .png or .jpg extension.  Thanks

**Comment by isaacgerg** [comment]
@planaria158 @rajshah4 

This issue is closed.  Please open another issue otherwise the author won't see the problem. Be sure you are using the latest quiver_engine.
